<%=chart :bar %>
  <%=comp :axis_category %>
    shadow:                 low
    size:                     8
    alpha:                   75
    orientation:  diagonal_down

  <%=comp :axis_ticks %>
    value_ticks:           1
    minor_color:      555555
    major_thickness:       1
    major_color:      000000
    category_ticks:        1
    minor_thickness:       1

  <%=comp :axis_value %>
    shadow:     low
    steps:        2
    size:         9
    alpha:       65
    max:        100
    color:   000000
    min:          0
    suffix:       %

  <%=comp :chart_border %>
    top_thickness:          0
    bottom_thickness:       0
    left_thickness:         3
    color:             000000
    right_thickness:        1

  <%=comp :chart_grid_v %>
    alpha:           5
    thickness:       5
    color:      000000

  <%=comp :chart_rect %>
    x:                  100
    positive_alpha:      10
    y:                   30
    height:             150
    positive_color:  000066
    negative_color:  000000
    negative_alpha:      30
    width:               60

  <%=comp :draw %>
    components:
      - <%= drawing :text %>
          shadow:      high
          alpha:         15
          rotation:     -90
          size:          60
          x:            -10
          y:            302
          color:     000000
          height:       150
          width:        400
          text:      'bandwidth'
      - <%= drawing :text %>
          alpha:       20
          size:       150
          x:           46
          y:          170
          color:   ffffff
          height:     150
          width:      400
          text:    '    >>'
      - <%= drawing :line %>
          line_alpha:             100
          y1:                     138
          x1:                      50
          y2:                     138
          x2:                     200
          line_color:          99bbee
          line_thickness:          25
          layer:           background
          text:            '          '
      - <%= drawing :circle %>
          radius:                 135
          line_alpha:             100
          x:                      350
          fill_alpha:               0
          y:                      140
          line_color:          99bbee
          line_thickness:          25
          layer:           background
          text:            '          '

  <%=comp :filter %>
    filters:
      - <%= filter_type :shadow %>
          blurY:       4
          angle:      45
          alpha:      50
          id:        low
          color:       0
          distance:    2
          blurX:       4
      - <%= filter_type :shadow %>
          blurY:       10
          angle:       45
          alpha:       50
          id:        high
          color:        0
          distance:     5
          blurX:       10

  <%=comp :legend %>
    layout:  hide

  <%=comp :link_data %>
    wheel_x:         210
    wheel_y:         138
    url:             '/composites/refresh_composite_bar'
    spinning_wheel:  true
    target:          update

  <%=comp :context_menu %>
    full_screen:  false

  <%=comp :series_color %>
    colors: ff4488

  <%=comp :series %>
    set_gap:  30