<%=chart :line %>

  <%=comp :axis_category %>
    shadow:  medium
    size:        16
    alpha:       85

  <%=comp :axis_ticks %>
    value_ticks:       false
    minor_color:      222222
    minor_count:           1
    major_thickness:       2
    position:         inside
    category_ticks:     true
    minor_thickness:       1

  <%=comp :axis_value %>
    shadow:    medium
    steps:          6
    size:          10
    alpha:         65
    min:          -40
    color:     ffffff
    show_min:   false

  <%=comp :chart_note %>
    background_color:  aaff00
    shadow:            medium
    size:                  11
    alpha:                 70
    x:                    -10
    background_alpha:      75
    y:                    -34
    type:                flag
    color:             000000
    
  <%=comp :tooltip %>
    background_color:  8888FF
    shadow:            medium
    alpha:                 90
    background_alpha:      90
    color:             FFFFFF    
    
  <%=comp :chart_grid_h %>
    alpha:      10
    thickness:   1

  <%=comp :chart_guide %>
    alpha:             25
    thickness:          1
    text_h_alpha:       0
    text_v_alpha:       0
    horizontal:      true
    vertical:        true
    type:          dashed

  <%=comp :chart_label %>
    background_color:  aaff00
    size:                  12
    alpha:                 80
    color:             000000
    position:          cursor

  <%=comp :chart_pref %>
    point_size:           7
    fill_shape:       false
    point_shape:     circle
    line_thickness:       2

  <%=comp :chart_rect %>
    shadow:            high
    x:                   50
    positive_alpha:      65
    y:                  100
    height:             150
    positive_color:  ffffee
    negative_color:  ff8888
    bevel:           bevel1
    negative_alpha:      65
    width:              320

  <%=comp :chart_transition %>
    delay:             .5
    order:         series
    type:      slide_left
    duration:         0.5

  <%=comp :draw %>
    components:
      - <%= drawing :text %>
          shadow:          high
          alpha:             10
          size:              48
          x:                  8
          delay:              0
          y:                  8
          height:            75
          h_align:       center
          duration:         0.5
          transition:  dissolve
          width:            400
          v_align:       bottom
          text:        'annual report'
      - <%= drawing :image %>
          alpha:                           90
          x:                              340
          delay:                            1
          y:                              225
          url:         charts/full_screen.swf
          height:                          15
          transition:                dissolve
          width:                           20
          text:        '                      '

  <%=comp :link %>
    areas:
      - <%=area :area %>
          x:                    340
          y:                    225
          width:                 20
          height:                15
          target: toggle_fullscreen
          tooltip: Full Screen Mode

  <%=comp :filter %>
    filters:
      - <%= filter_type :shadow %>
          blurY:       5
          angle:      45
          alpha:      20
          id:        low
          distance:    2
          blurX:       5
      - <%= filter_type :shadow %>
          blurY:          7
          angle:         45
          alpha:         40
          id:        medium
          distance:       2
          blurX:          7
      - <%= filter_type :shadow %>
          blurY:       10
          angle:       45
          alpha:       25
          id:        high
          distance:     5
          blurX:       10
      - <%= filter_type :bevel %>
          blurY:               15
          angle:               45
          highlightAlpha:      25
          type:             outer
          id:              bevel1
          highlightColor:  ffffff
          shadowAlpha:         50
          blurX:               15
          distance:             5

  <%=comp :legend %>
    shadow:                 low
    size:                    13
    alpha:                   75
    line_alpha:               0
    x:                       50
    bullet:                line
    fill_alpha:              10
    delay:                    0
    y:                       75
    margin:                   5
    line_color:          000000
    height:                   5
    color:               ffffff
    fill_color:          000000
    duration:               0.5
    line_thickness:           0
    transition:        dissolve
    width:                  320
    layout:          horizontal

  <%=comp :series_color %>
    colors: ff4422,ffee00,8844ff

  <%=comp :series_explode %>
    numbers: 400