<%= chart :pie_threed %>
  <%=comp :chart_label %>
    shadow:            low
    as_percentage:    true
    alpha:              65
    size:               10
    position:       inside

  <%=comp :chart_pref %>
    rotation_x:     50
    drag:        false
    select:       true

  <%=comp :chart_rect %>
    x:                85
    positive_alpha:    0
    y:                50
    height:          180
    width:           300

  <%=comp :chart_type %>

  <%=comp :draw %>
    components:
      - <%= drawing :rect %>
          x:                        0
          y:                        0
          height:                 300
          fill_color:          4c5577
          bevel:                   bg
          line_thickness:           0
          layer:           background
          width:                  400
          text:            '          '
      - <%= drawing :text %>
          shadow:        high
          alpha:           10
          size:           113
          x:              -98
          y:              192
          color:            0
          height:         150
          layer:   background
          width:          500
          text:    '   contest'
      - <%= drawing :text %>
          shadow:       low
          alpha:         10
          rotation:     -90
          size:          85
          x:            -10
          y:            280
          color:     ffffff
          height:        50
          width:        300
          text:      '  VOTE'
      - <%= drawing :circle %>
          radius:                 150
          line_alpha:               5
          x:                      220
          fill_alpha:               0
          y:                      120
          line_color:          000000
          line_thickness:          65
          layer:           background
          text:            '          '

  <%=comp :filter %>
    filters:
      - <%= filter_type :shadow %>
          blurY:       10
          angle:       45
          alpha:       50
          id:        high
          distance:     3
          blurX:       10
      - <%= filter_type :shadow %>
          blurY:      10
          angle:      45
          alpha:      60
          id:        low
          distance:    2
          blurX:      10
      - <%= filter_type :bevel %>
          blurY:             200
          angle:              90
          highlightAlpha:     15
          type:            inner
          id:                 bg
          shadowAlpha:        15
          blurX:               0
          distance:           50

  <%=comp :legend %>
    shadow:             low
    alpha:               75
    x:                   65
    fill_alpha:           0
    margin:              20
    y:                  -10
    height:              25
    color:           ffffff
    layout:      horizontal
    width:              345

  <%=comp :update %>
    delay:                     1
    mode:                   data
    url:    <%= options[:url] %>

  <%=comp :context_menu %>
    full_screen:  false