<%= chart :scatter %>

  <%=comp :axis_category %>
    shadow:              low
    size:                 12
    alpha:                85
    orientation:  horizontal
    color:            000000

  <%=comp :axis_ticks %>
    value_ticks:       false
    minor_color:      222222
    minor_count:           1
    major_thickness:       1
    major_color:      000000
    position:         inside
    category_ticks:     true
    minor_thickness:       0

  <%=comp :axis_value %>
    size:           10
    alpha:          60
    max:            12
    decimals:        0
    min:             0
    color:      ffffff
    show_min:    false

  <%=comp :chart_border %>
    top_thickness:          0
    bottom_thickness:       3
    left_thickness:         0
    color:             222222
    right_thickness:        0

  <%=comp :chart_grid_h %>
    alpha:          10
    thickness:       1
    color:      000000

  <%=comp :chart_grid_v %>
    alpha:          20
    thickness:       2
    type:       dotted
    color:      000000

  <%=comp :chart_label %>
    size:          12
    alpha:         85
    bold:        true
    color:     ff4400
    position:  cursor

  <%=comp :chart_guide %>
    radius:               6
    line_alpha:          90
    line_color:      ff4400
    line_thickness:       2

  <%=comp :chart_pref %>
    trend_thickness:   2
    point_size:        7
    trend_alpha:      20

  <%=comp :chart_rect %>
    corner_tr:           75
    x:                   75
    positive_alpha:      25
    corner_bl:            0
    y:                   75
    corner_tl:            0
    height:             150
    positive_color:  000000
    corner_br:            0
    width:              300

  <%=comp :chart_type %>

  <%=comp :draw %>
    components:
      - <%= drawing :rect %>
          shadow:             shadow1
          line_alpha:               0
          x:                        0
          fill_alpha:             100
          y:                        0
          height:                 300
          fill_color:          4c5e6f
          line_thickness:           0
          layer:           background
          width:                  400
          text:            '          '
      - <%= drawing :rect %>
          shadow:             shadow2
          line_alpha:               0
          corner_tr:               75
          x:                       75
          fill_alpha:             100
          y:                       75
          height:                 150
          fill_color:          000000
          line_thickness:           0
          layer:           background
          width:                  300
          text:            '          '
      - <%= drawing :text %>
          shadow:     high
          alpha:        30
          size:         35
          x:            75
          y:           238
          color:    ffffff
          height:      150
          h_align:    left
          width:       400
          v_align:     top
          text:     'Distance'
      - <%= drawing :text %>
          shadow:      high
          alpha:         30
          rotation:     -90
          size:          35
          x:              5
          y:            228
          color:     ffffff
          height:        60
          width:        200
          v_align:   bottom
          text:      ' Score'
      - <%= drawing :text %>
          shadow:       low
          alpha:          3
          rotation:     -10
          size:         100
          x:            140
          y:            200
          color:     ffffff
          text:      '     @'
      - <%= drawing :text %>
          shadow:       low
          alpha:          3
          rotation:      10
          size:         100
          x:           -125
          y:             75
          color:     ffffff
          text:      '     @'
      - <%= drawing :text %>
          shadow:       low
          alpha:          3
          rotation:      45
          size:         100
          x:            130
          y:           -120
          color:     ffffff
          text:      '     @'
      - <%= drawing :text %>
          shadow:       low
          alpha:          3
          rotation:     -45
          size:         100
          x:            -80
          y:             80
          color:     ffffff
          text:      '     @'
      - <%= drawing :text %>
          shadow:       low
          alpha:          3
          rotation:       0
          size:         100
          x:            210
          y:             40
          color:     ffffff
          text:      '     @'

  <%=comp :filter %>
    filters:
      - <%= filter_type :shadow %>
          inner:        true
          blurY:         200
          angle:         135
          alpha:          20
          id:        shadow1
          color:      000000
          quality:         1
          distance:       50
          blurX:         300
      - <%= filter_type :shadow %>
          blurY:           8
          angle:          70
          alpha:          35
          id:        shadow2
          knockout:     true
          distance:        7
          blurX:          12
      - <%= filter_type :shadow %>
          blurY:       5
          angle:      45
          alpha:      50
          id:        low
          distance:    2
          blurX:       5
      - <%= filter_type :shadow %>
          blurY:       10
          angle:       45
          alpha:       75
          id:        high
          distance:     5
          blurX:       10

  <%=comp :legend %>
    shadow:               low
    line_alpha:             0
    size:                  12
    alpha:                 75
    x:                     75
    fill_alpha:             0
    y:                     30
    margin:                 3
    line_color:        000000
    height:                35
    fill_color:        ffffff
    color:             ffffff
    line_thickness:         0
    width:                 10
    layout:          vertical

  <%=comp :series_color %>
    colors: 88ff00,ff8800