<%= chart :stacked_column %>
  <%=comp :update %>
    url:   <%= options[:url] %>
    delay: 4
    
  <%=comp :axis_category %>
    shadow:     low
    size:        12
    alpha:       75
    color:   000022
    skip:         2

  <%=comp :axis_value %>
    shadow:       low
    steps:          4
    size:          10
    alpha:         75
    max:          120
    color:     ffffee
    show_min:   false

  <%=comp :chart_border %>
    top_thickness:          1
    bottom_thickness:       1
    left_thickness:         1
    color:             000000
    right_thickness:        1
  <%=comp :chart_guide %>
    radius:                 3
    background_color:  FF4400
    alpha:                 50
    line_alpha:             0
    thickness:              1
    fill_alpha:            75
    text_h_alpha:          80
    horizontal:          true
    vertical:           false
    type:              dashed
    suffix_h:            ,000
    color:             ffffff
    fill_color:        FF4400
    prefix_h:               $

  <%=comp :chart_rect %>
    x:                   60
    positive_alpha:      50
    y:                   50
    height:             200
    positive_color:  99dd44
    bevel:               bg
    width:              300

  <%=comp :draw %>
    components:
      - <%= drawing :text %>
          shadow:     high
          alpha:        75
          size:         42
          x:            60
          y:             6
          color:    ffffee
          height:       50
          h_align:    left
          width:       300
          v_align:  bottom
          text:     'monthly report'
      - <%= drawing :text %>
          shadow:      low
          alpha:        75
          size:         14
          x:            60
          y:            50
          color:    333333
          height:      300
          h_align:   right
          width:       296
          v_align:     top
          text:     <%= options[:month] %>
      - <%= drawing :text %>
          shadow:      low
          alpha:         5
          size:         30
          x:             0
          y:           150
          color:    000000
          height:      150
          h_align:  center
          width:       400
          v_align:  bottom
          text:     '|||||||||||||||||||||||||||||||||||||||||||||||'

  <%=comp :filter %>
    filters:
      - <%= filter_type :shadow %>
          blurY:       10
          angle:       45
          alpha:       20
          id:        high
          distance:     5
          blurX:       10
      - <%= filter_type :shadow %>
          blurY:       5
          angle:      45
          alpha:      35
          id:        low
          distance:    3
          blurX:       5
      - <%= filter_type :bevel %>
          blurY:               50
          angle:               10
          highlightAlpha:      60
          type:              full
          id:                  bg
          highlightColor:  ffffff
          shadowAlpha:         30
          blurX:               50
          distance:            10

  <%=comp :legend %>
    layout:  hide

  <%=comp :context_menu %>
    full_screen:  false

  <%=comp :series_color %>
    colors: 4e627c,cc7744

  <%=comp :series %>
    set_gap:  2