development:
  adapter: mysql
  database: rails_dev
  username: root
  password: 
  host: localhost

test:
  adapter: mysql
  database: rails_test
  username: root
  password: 
  host: localhost

production:
  adapter: mysql
  database: rails_dev
  username: root
  password: 
  host: localhost
  
